In [3]:
# 1. Array Creation
# Create a 1-dimensional array of integers from 1 to 10.
import numpy as np

In [7]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
# Create a 2-dimensional array with random float values of shape (3, 4).\
b = np.random.rand(2,3)
print(b)

[[0.49265358 0.0288548  0.75163797]
 [0.83423944 0.11994877 0.51370653]]


In [7]:
# Create a 3-dimensional array of zeros with shape (2, 3, 4).
c = np.zeros((2,3,4))
print(c)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [15]:
# 2. Array operation
# Given two 1-dimensional arrays, perform element-wise addition,subtraction, multiplication, and division.
op1 = np.array([3,5,8])
op2 = np.array([2,7,10])
sum = op1+op2
diff = op1-op2
product = op1*op2
div = op1/op2
print(sum)
print(diff)
print(product)
print(div)

[ 5 12 18]
[ 1 -2 -2]
[ 6 35 80]
[1.5        0.71428571 0.8       ]


In [19]:
# Calculate the mean, median, and standard deviation of a given 1-dimensional array.
s = ([1,2,3,4,5,6,7,8,9,10])
mean_s = np.mean(s)
median_s = np.median(s)
std_deviation = np.std(s)
print(mean_s)
print(median_s)
print(std_deviation)

5.5
5.5
2.8722813232690143


In [29]:
# Reshape a 1-dimensional array into a 2-dimensional array of shape (3,4).
d = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a = d.reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
# 3. Array Indexing and slicing
# Extract the first row and last column of a 2-dimensional array.
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
ext_1st = a[0,:]
ext_last = a[:,2]
#print(a)
print(ext_1st)
print(ext_last)

[1 2 3]
[3 6 9]


In [15]:
#Reverse the order of elements in a 1-dimensional array.
a = np.array([1,2,3,4,5,6,7,8,9])
rev = a[::-1]     # start:stop:step
print(rev)

[9 8 7 6 5 4 3 2 1]


In [17]:
# Select elements from a 2-dimensional array that satisfy a specific condition (e.g., values greater than a certain threshold).
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
condition = a>5
print(condition)
b = a[condition]
print(b)

[[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]


In [19]:
# 4. Array Broadcasting
# Add a scalar value to each element of a 2-dimensional array.
a = np.array([[4,7,1],[6,9,10]])
sca_value = 15
b = a + sca_value
print(b)

[[19 22 16]
 [21 24 25]]


In [21]:
#Multiply a 1-dimensional array with a 2-dimensional array, leveraging NumPy's broadcasting rules.
a = np.array([1,2,3,4])
b = np.array([[5,2,7,1],[4,7,2,3]])
c = a*b
print(c)


[[ 5  4 21  4]
 [ 4 14  6 12]]


In [23]:
# 5. Linear Algebra
# Calculate the dot product of two 1-dimensional arrays.
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
dot_product = np.dot(a,b)
print(dot_product)


130


In [29]:
#Compute the matrix multiplication of two 2-dimensional arrays.
a = np.array([[4,5],[1,2]])
b = np.array([[3,7],[2,1]])
mat_mul = np.dot(a,b)
mat_mul1 = a @ b
print(mat_mul)
print(mat_mul1)

[[22 33]
 [ 7  9]]
[[22 33]
 [ 7  9]]


In [37]:
# Find the inverse and determinant of a square matrix.
a = np.array([[1,2,9],[4,7,4],[10,8,9]])
det_a = np.linalg.det(a)
inv_a = np.linalg.inv(a)
print(det_a)
print(inv_a)

-303.00000000000017
[[-0.10231023 -0.17821782  0.18151815]
 [-0.01320132  0.26732673 -0.10561056]
 [ 0.12541254 -0.03960396  0.00330033]]
