In [17]:
import numpy as np
scalar = np.array(10)
print(scalar.shape)

()


In [21]:
vector = np.array([1,2,3])
print(vector.shape)

(3,)


In [23]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [43]:
arr = np.linspace(0, 20, num=5)
print(arr)



[ 0.  5. 10. 15. 20.]


In [45]:
arr = np.arange(2,20,4)

In [49]:
print(arr)

[ 2  6 10 14 18]


In [51]:
arr = np.array([1,2,3])
result = (arr>1) & (arr<3)
print(result)
arr1 = arr[result]
print(arr1)

[False  True False]
[2]


In [53]:
lst = [1,2,3,4,5]
arr1 = np.array(lst)
arr2 = np.asarray(lst)
print(arr1)
print(arr2)

[1 2 3 4 5]
[1 2 3 4 5]


In [59]:
input = np.array([4,5,6])
arr1 = np.array(input) # creates new array
arr2 = np.asarray(input) # reuses the original array
print(arr1 is input)
print(arr2 is input)


False
True


In [61]:
original = np.array([1,2,3,4,5])
arr1 = np.array(original)
arr1[0] = 50
print(original)
print(arr1)

[1 2 3 4 5]
[50  2  3  4  5]


In [67]:
original = np.array([6,7,8,9])
arr2 = np.asarray(original)
arr2[0] = 50
print(original)
print(arr2)

[50  7  8  9]
[50  7  8  9]


In [86]:
import time
# using numpy
arr = np.arange(1000000)
start = time.time()
result = arr*2
end = time.time()
print(f"NumPy time:{end-start}")

# using lists
lst = list(range(1000000))
start = time.time()
result = [x*2 for x in lst]
end = time.time()
print(f"List time: {end-start}")


NumPy time:0.015156984329223633
List time: 0.04729485511779785


In [110]:
arr = np.array([1,2,3,4,5])
np.save('arr.npy',arr)
b = np.load('arr.npy')
print(b)


[1 2 3 4 5]


In [106]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
np.savez('save.npz', array1=a, array2=b)
c = np.load('save.npz')
c

NpzFile 'save.npz' with keys: array1, array2

In [112]:
arr = np.array([2,5,8,10,12])
result = np.where(arr<5,0,1)
print(result)

[0 1 1 1 1]


In [120]:
a = np.array([1,0,5,6,0,0,2])
index = np.where(a!=0)
print(index)

(array([0, 2, 3, 6]),)
